Iter13
xoxloviwan/go-monitor pull request #13
Opened 2024-08-14 07:52 UTC by xoxloviwan

2024-08-18 23:21 UTC, vokinneberg requested changes
Ура, первое ревью третьего спринта! 🎉 В этом спринте наше приложение стало еще сложнее, добавился новый слой БД 💪 Мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Ты консистентно встроил функционал в структуру существующего приложения. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. По условию задачи на стороне агента также должен быть реализован retry в случае получения retriable ошибки. *Агент не сумел с первой попытки выгрузить данные на сервер из-за временной невозможности установить соединение с сервером*.
2. Было бы здорово реализовать проверку кейса с конфликтом с существующим URL.

2024-08-18 23:21 UTC, vokinneberg commented on cmd/agent/main.go
> +func send(adr string, msgs api.MetricsList) (err error) {
По условию задачи на стороне агента так же должен быть реализован retry в случае получения retriable ошибки.  _Агент не сумел с первой попытки выгрузить данные на сервер из-за временной невозможности установить соединение с сервером_.

2024-08-18 23:21 UTC, vokinneberg commented on internal/store/store.go
> +	err := ctx.Err()
Проверять контекст таким образом можно, но основное назначение контекста при передаче в метод это прерывание длительной операции. Можно попробовать улучшить проверку контекста при выполнении каждой итерации:
```go
	metrics := make(mtr.MetricsList, 0, len(*m))

	for _, v := range *m {
		select {
		case <-ctx.Done():
			return fmt.Errorf("context canceled during processing: %w", ctx.Err())
		default:
			var metric mtr.Metrics
			if v.MType == GaugeName {
				metric = mtr.Metrics{
					ID:    v.ID,
					MType: GaugeName,
					Value: new(float64),
				}
				*metric.Value = s.Gauge[v.ID]
			} else if v.MType == CounterName {
				metric = mtr.Metrics{
					ID:    v.ID,
					MType: CounterName,
					Delta: new(int64),
				}
				*metric.Delta = s.Counter[v.ID]
			}
			metrics = append(metrics, metric)
		}
	}
```

2024-08-18 23:21 UTC, vokinneberg commented on internal/store/db.go
> +		err = br.Close()
Так же можно вызвать при помощи `defer`.

2024-08-18 23:21 UTC, vokinneberg commented on internal/store/db.go
> +		log.Printf("%s Retry %d ...", err.Error(), retry+1)
Думаю здесь так же cтоит использовать `slog`?

2024-08-18 23:21 UTC, vokinneberg commented on internal/store/db.go
> +	*m = mtr.MetricsList{}
Если честно вызывает вопросы такое использование параметра m. Во-первых я бы рекомендовал все же именовать параметры более информативно. Однобуквенные имена допустимы для локальных переменных, в случае с параметрами это может ухудшать читаемость кода. Во-вторых не очень понятно, зачем мы инициализируем параметр заново? Может быть возвращать коллекцию как возращаемое значение из метода проще, чем модифицировать ее да еще и таким способом?

2024-08-18 23:21 UTC, vokinneberg commented on internal/api/router.go
> +	if cfg.StoreInterval == 0 {
Не совсем понял, что делает эта конструкция?

2024-08-19 04:28 UTC, xoxloviwan commented on internal/api/router.go
> +	if cfg.StoreInterval == 0 {
Это крайний случай, когда значение `STORE_INTERVAL=0` делает запись синхронной.
В 9ом инкременте не было учтено https://github.com/xoxloviwan/go-monitor/pull/9#discussion_r1702429328

2024-08-19 04:34 UTC, xoxloviwan commented
> 2. Было бы здорово реализовать проверку кейса с конфликтом с существующим URL.
Это замечание не понял... может это относится к заданию про short url, а не metrics?

2024-08-21 05:00 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью третьего спринта! 🙌 Ты реализовал мои некоторые мои предложения. Отличная работа! 🚀 Тем не менее я бы хотел обратить внимание на пару аспектов:

1. Так как мы уже используем структурный логгер я бы рекомендовал избавиться от `log.Println()`
2. Как мы и обсуждали, сюда следовало бы добавить проверку типа ошибки в агенте для ретрая в соотвествии с постановкой задачи. Предлагаю разобраться с этим в следующем спринте!

2024-08-21 05:00 UTC, vokinneberg commented on cmd/agent/main.go
> +	for err != nil && retry < 3 {
Как мы и обсуждали, сюда следовало бы добавить проверку типа ошибки в соотвествии с постановкой задачи. Предлагаю разобраться с этим в следующем спринте! 😊

2024-08-21 05:48 UTC, merged