sprint 7
xoxloviwan/go-monitor pull request #16
Opened 2024-10-25 16:46 UTC by xoxloviwan

2024-10-30 03:55 UTC, vokinneberg requested changes
Поздравляю с первым ревью седьмого спринта! 🎉 Этот спринт даёт возможность немного отдохнуть от написания кода и при этом попробовать на практике интересные инструменты. ⚡ Ты сделал улучшения своего приложения, и оно проходит автотесты. 👍 Тем не менее, по традиции хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Ты добавил Makefile. 👍
2. Твой код отформатирован с использованием `gofmt` и `goimports`.
3. Ты реализовал примеры и бенчмарки. 💪
4. Ты добавил документацию в формате `godoc`. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Было бы здорово добавить автоматическое вычисление покрытия в CI pipeline при помощи GitHub Actions. Можно также добавить badge, который будет показывать процент покрытия тестами проекта, в README файл. Как это сделать, можно посмотреть, например, здесь:
2. Файлы `internal/metrics_types/api_easyjson.go` и `internal/metrics_types/api_easyjson.go`, кажется, не отформатированы при помощи `goimports`.
3. Покрытие тестами сейчас на проекте 31.3%, в то время как по условию задачи должно быть ≥ 40%.
4. Так как большая часть спринта была посвящена паттернам, было бы здорово если бы ты попробовал применить какой-нибудь из них в своем приложении.

2024-10-30 03:55 UTC, vokinneberg commented on internal/api/handler.go
> +func NewHandler(store ReaderWriter) *Handler {
Если все методы не экспортируемые, наверное и конструктор стоит сделать не э
кспортитуемым?

2024-10-30 07:15 UTC, xoxloviwan commented
> 2\. Файлы `internal/metrics_types/api_easyjson.go` и `internal/metrics_types/api_easyjson.go`, кажется, не отформатированы при помощи `goimports`.
Это сгенерированный код. Нужно ли это там?
`// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.`


> 3\. Покрытие тестами сейчас на проекте 31.3%, в то время как по условию задачи должно быть ≥ 40%.

Если считать покрытие "в лоб", то в него попадают всевозможные моки и сгенерированные файлы, мне кажется учитывать их в покрытии некорректно...

2024-11-02 22:34 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью седьмого спринта! 🎉 Текущее покрытие тестами действительно считается, как 34.2%. Попробуй посмотреть в html версии отчета, что именно не покрыто `go tool cover -html=profile.cov`.

2024-11-04 20:41 UTC, merged