sprint 9 Iter23
xoxloviwan/go-monitor pull request #18
Opened 2024-11-17 19:41 UTC by xoxloviwan

2024-11-20 04:18 UTC, vokinneberg requested changes
Поздравляю с первым ревью девятого спринта! 🎉 Продолжаем улучшать наше приложение и покрывать его тестами! ⚡ По традиции хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Ты реализовал функционал, требующийся по ТЗ 👍
2. Ты улучшил покрытие кода тестами 🙌

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Если честно в Router у нас получилось все очень сложно и мне стало тяжело разбираться, что же происходит и для чего. Я набросал свои идеи, как можно было бы улучить реализацию - это не финальная версия, я ее не проверял, но ее можно использовать, как базу. Приходи 1 на 1 - разберем все и обсудим.
2. В `main` мне кажется можно избавить от флага и использовать `WaitGroup`

2024-11-20 04:18 UTC, vokinneberg commented on internal/config_agent/conf.go
> +	if cfg.ConfigPath != *config && cfg.ConfigPath == "" {
Тут стоит добавить проверку `config != nil` перед тем как разименовывать указатель иначе можно нарваться на `nil pointer` панику.

2024-11-20 04:18 UTC, vokinneberg commented on internal/config_agent/conf.go
> +	redefineConf(&cfgDefaults, Config{
Не совсем понял для чего вызывать `redefineConf(...)` два раза?

2024-11-20 04:18 UTC, vokinneberg commented on cmd/agent/main.go
> +		slog.Warn(fmt.Sprintf("worker #%d: %s Retry %d ...", workerID, err.Error(), retry+1))
Такая строка будет больше в `slog` стиле.
```suggestion
		slog.Warn("Retry attempt", "worker", workerID, "error", err, "retry", retry+1)
```

2024-11-20 04:18 UTC, vokinneberg commented on cmd/agent/main.go
> +	var shutdown bool
Мне кажется можно избавить от флага и использовать `WaitGroup`:

```go
	var wg sync.WaitGroup
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
	for {
		// Здесь произойдет lock и select разлочится событием, которое произойдет первым.
		select {
		case <-pollTicker.C:
			pollCount += 1
			metrics = metrs.GetMetrics(pollCount)
		case <-sendTicker.C:
			msgCh := metrics.MakeMessages()
			dests := SplitBatch(msgCh, cfg.RateLimit) // Fan Out

			wg.Add(len(dests)) // не закроются выходные каналы
			for i, ch := range dests {
				go func(worker int, d <-chan api.Metrics) {
					defer wg.Done()
					subbatch := make([]api.Metrics, 0)
					for val := range d {
						subbatch = append(subbatch, val)
					}
					if len(subbatch) > 0 {
						slog.Info(fmt.Sprintf("worker #%d got %+v\n", worker, subbatch))
						err := send(worker, cfg.Address, subbatch, cfg.Key, publicKey)
						if err != nil {
							slog.Error(fmt.Sprintf("worker #%d error: %s\n", worker, err.Error()))
						}
					}
				}(i, ch)
			}
			wg.Wait()
			slog.Info("Jobs done")
			return
		case <-quit:
			wg.Wait()
			return
		}
	}
```

2024-11-20 04:18 UTC, vokinneberg commented on internal/api/router.go
> +	quit := make(chan os.Signal, 1)
Если честно в этом файле у нас получилось все очень сложно и мне стало тяжело разбираться, что же происходит и для чего. Я набросал свои идеи, как можно было бы улучить реализацию - это не финальная версия, я ее не проверял, но ее можно использовать, как базу. Приходи 1 на 1 - разберем все и обсудим:

```Go
package api

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/xoxloviwan/go-monitor/internal/store"
	"golang.org/x/sync/errgroup"

	asc "github.com/xoxloviwan/go-monitor/internal/asymcrypto"
	config "github.com/xoxloviwan/go-monitor/internal/config_server"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// Backuper is an interface for backing up data.
//
// It provides a method for saving the data to a file.
type Backuper interface {
	SaveToFile(path string) error
}

// DBStorage is an interface for database storage.
//
// It provides methods for restoring data from a file and implementing the ReaderWriter interface.
type DBStorage interface {
	RestoreFromFile(path string) error
	ReaderWriter
}

// Storage is an interface that combines Backuper and DBStorage.
//
// It provides methods for backing up data and restoring data from a file.
type Storage interface {
	DBStorage
}

//go:generate mockgen -destination ./mock_router.go -package api github.com/xoxloviwan/go-monitor/internal/api Router

// Router interface for API server.
type Router interface {
	SetupRouter(ping gin.HandlerFunc, dbstore ReaderWriter, logLevel slog.Level, key []byte, privateKey *asc.PrivateKey)
	Run(addr string) error
	Shutdown()
}

// RunServer runs the API server with the given configuration.
//
// It sets up the routes, middleware, and logging, and starts the server.
func RunServer(r Router, cfg config.Config) error {
	var (
		s           Storage
		pingHandler gin.HandlerFunc
	)

	// Если DSN не пустой, то используем базу данных.
	if cfg.DatabaseDSN != "" {
		db, err := sql.Open("pgx", cfg.DatabaseDSN)
		if err != nil {
			return err
		}
		defer db.Close()
		pingHandler = func(c *gin.Context) {
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer cancel()
			if err := db.PingContext(ctx); err != nil {
				c.Error(err)
				c.Status(http.StatusInternalServerError)
				return
			}
			c.Status(http.StatusOK)
		}
		dbs := store.NewDBStorage(db)
		err = dbs.CreateTable()
		if err != nil {
			return fmt.Errorf("create table error: %v", err)
		}
		s = dbs
	} else {
		// Если DSN пустой, то используем память.
		pingHandler = func(c *gin.Context) {
			c.Status(http.StatusOK)
		}
		s = store.NewMemStorage()
	}

	if cfg.Restore && cfg.FileStoragePath != "" {
		if err := s.RestoreFromFile(cfg.FileStoragePath); err != nil {
			slog.Warn("Restore failed", slog.Any("error", err.Error()))
		}
	}

	var pKey *asc.PrivateKey
	if cfg.CryptoKey != "" {
		var err error
		if pKey, err = asc.GetPrivateKey(cfg.CryptoKey); err != nil {
			return fmt.Errorf("get private key error: %v", err)
		}
	}

	// Настраиваем маршруты.
	r.SetupRouter(pingHandler, s, slog.LevelDebug, []byte(cfg.Key), pKey)

	// Запускаем сервер в отдельной горутине.
	var eg errgroup.Group
	eg.Go(func() error {
		return r.Run(cfg.Address)
	})

	// Создаем канал для сигналов завершения.
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)

	// Запускаем периодическое сохранение данных в файл.
	if cfg.StoreInterval > 0 {
		eg.Go(func() error {
			backupTicker := time.NewTicker(time.Duration(cfg.StoreInterval) * time.Second)
			defer backupTicker.Stop()
			for {
				select {
				case <-backupTicker.C:
					// Если объект реализует интерфейс Backuper, то сохраняем данные в файл.
					if b, ok := s.(Backuper); ok {
						if err := backupData(b, cfg.FileStoragePath); err != nil {
							return fmt.Errorf("backup data error: %v", err)
						}
					}
				case <-quit:
					return nil
				}
			}
		})
	}

	// Ждем сигнала завершения.
	<-quit

	// Завершаем работу сервера.
	r.Shutdown()

	// Делем одноразовое сохранение данных в файл при завершении работы.
	if b, ok := s.(Backuper); ok {
		if err := backupData(b, cfg.FileStoragePath); err != nil {
			return fmt.Errorf("backup data error: %v", err)
		}
	}

	// Ждем завершения всех горутин и возвращаем ошибку, если она произошла.
	if err := eg.Wait(); err != nil {
		return fmt.Errorf("goroutines error: %v", err)
	}
	return nil
}

// RouterImpl is wrap for gin.Engine and http.Server
type RouterImpl struct {
	*gin.Engine
	srv *http.Server
}

// NewRouter returns a new Router instance.
func NewRouter() *RouterImpl {
	return &RouterImpl{gin.New(), nil}
}

// SetupRouter sets up routes and middleware.
//
// The engine is initialized with the given ping handler, store, log level, and key.
func (r *RouterImpl) SetupRouter(ping gin.HandlerFunc, dbstore ReaderWriter, logLevel slog.Level, key []byte, privateKey *asc.PrivateKey) {
	handler := newHandler(dbstore)
	r.Use(compressGzip())
	r.Use(logger(logLevel))
	if len(key) > 0 {
		r.Use(verifyHash(key))
	}
	if privateKey != nil {
		r.Use(decryptBody(privateKey))
	}
	r.POST("/update/:metricType/:metricName/:metricValue", handler.update)
	r.POST("/update/", handler.updateJSON)
	r.POST("/updates/", handler.updateJSON)
	r.GET("/value/:metricType/:metricName", handler.value)
	r.POST("/value/", handler.valueJSON)
	r.GET("/", handler.list)

	r.GET("/ping", ping)
}

// Run starts the server listening on the specified address.
func (r *RouterImpl) Run(addr string) error {
	r.srv = &http.Server{
		Addr:    addr,
		Handler: r.Handler(),
	}
	return r.srv.ListenAndServe()
}

// Shutdown gracefully shuts down the server.
func (r *RouterImpl) Shutdown() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := r.srv.Shutdown(ctx); err != nil {
		slog.Error("Server Shutdown:", slog.Any("error", err))
		return
	}
}

func backupData(b Backuper, path string) error {
	return b.SaveToFile(path)
}
```

2024-11-20 04:18 UTC, vokinneberg commented on internal/api/router.go
> +	<-ctx.Done()
Тут уже нет смысла ожидать таймаута, так как `Shutdown()` вернула управление.

2024-11-23 15:42 UTC, xoxloviwan commented on internal/config_agent/conf.go
> +	redefineConf(&cfgDefaults, Config{
```
// Если указана переменная окружения, то используется она.
// Если нет переменной окружения, но есть аргумент командной строки (флаг), то используется он.
// Если нет ни переменной окружения, ни флага, то используется значение по умолчанию.
// Если есть файл конфигурации, то значения из файла конфигурации должны иметь меньший приоритет, чем флаги или переменные окружения.
// env > flag > file > default
```
Чтобы реализовать эти требования, сделал функцию которая берет две структуры с типом `Config`, при этом значения первой структуры всегда менее приоритетны и "накрываются" значениями второй. Первая передается по ссылке и меняется при каждом вызове `redefineConf()`

2024-11-23 15:57 UTC, xoxloviwan commented
Доработал реализацию `router.go`, идеи которой были предложены здесь 9c8b369e5067de8feff2178695b85ad8a4ca1e15

Решил проверить еще раз всю реализацию по автотестам `iter1` - `iter14`, так как изменения `router.go` значительные.

1. Выявил ситуацию, когда cервер останавливался с ошибкой при значениях `RESTORE=true` и заполненном `FILE_STORAGE_PATH`, если файл бэкапа не был создан, исправил здесь 4fc67d0bafde6619376cd15c9696f73ea4c2e514
2. Обнаружил ошибку в iter14 race condition при запуске тестов из `internal/metrics/metrics_test.go` - проблема оказалась `/internal/metrics/metrics.go` в "общей" переменной `error`, которая могла меняться во всех goрутинах.

Были проблемы с запуском тестов `go test -race ./...` 
```
$ go test ./... -count=1 -race -vet=off
go: -race requires cgo; enable cgo by setting CGO_ENABLED=1

$ export  CGO_ENABLED=1

$ go test -count=1 -race -vet=off ./...
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
```
Не понял почему это требовалось, но пришлось установить gcc через mingw на windows...

2024-11-26 00:32 UTC, vokinneberg reviewed
Поздравляю с успешным ревью девятого спринта! 🎉 Ты значительно улучшил структуру приложения 👍 Так держать! 🙌 Единственное пожелание на следующий спринт — повысить процент покрытия приложения тестами. 🆙

2024-11-26 00:32 UTC, vokinneberg approved these changes

2024-11-26 05:52 UTC, merged