Iter9
xoxloviwan/go-monitor pull request #9
Opened 2024-07-29 08:44 UTC by xoxloviwan

2024-08-03 01:54 UTC, vokinneberg requested changes
Поздравляю с успешным ревью второго спринта! 🤗 В этом спринте мы охватили большой и важный материал, а наше приложение усложнилось. 💪 Ты справился с реализацией и реализовал все в соответствии с постановкой задачи. Отличная работа! 🚀 Тем не менее мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Твой код лаконичен, его легко читать и понимать. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Кажется, твоя реализация сохранения метрик в файл не совсем соответствует постановке задачи: *по умолчанию 300 секунд, значение 0 делает запись синхронной*. В такой реализации при `0` запись все же не будет синхронной (более того, будет ли работать тикер в такой ситуации вообще?), стоит подумать о том, как это реализовать.
2. Было бы здорово реализовать тесты для новых ручек, которые были добавлены в этом спринте.

2024-08-03 01:54 UTC, vokinneberg commented on cmd/agent/main.go
> +func send(adr *string, msgs []api.Metrics) (err error) {
Мне кажется тут для строки передача указателя это лишнее, так как строка не меняется а копирование в данном случае это не проблема. Передача указателя (по ссылке) скорее оправдана в случае структур, а не элементарных типов.

2024-08-03 01:54 UTC, vokinneberg commented on cmd/agent/main.go
> +	}
Я бы советовал вызвать метод  `Close(...)`  сразу после создания Writer, так как если паника произойдет между созданием и вызовом defer, он выполнен не будет. 

```suggestion
	w := gzip.NewWriter(&b)
	defer func() {
	         // обязательно нужно вызвать метод Close() — в противном случае часть данных
	        // может не записаться в буфер b; если нужно выгрузить все упакованные данные
	        // в какой-то момент сжатия, используйте метод Flush()
	    	if err := w.Close(); err != nil {
	    	    return nil, fmt.Errorf("failed compress data: %v", err)
	    	}
	 }
	// запись данных
	_, err := w.Write(data)
	if err != nil {
		return nil, fmt.Errorf("failed write data to compress temporary buffer: %v", err)
	}
```

2024-08-03 01:54 UTC, vokinneberg commented on internal/api/router.go
> +	go func() {
👍 за реализацию. Советую посмотреть в сторону  `errgroup.Group{}` - с ней может быть проще запускать горутины, которые возвращают ошибки.

2024-08-03 01:54 UTC, vokinneberg commented on internal/api/router.go
> +	for {
Кажется эта реализация не совсем соответствует постановке задачи: _по умолчанию 300 секунд, значение 0 делает запись синхронной_. В такой реализации при `0` запись все же не будет синхронной (более того, будет ли работать тикер в такой ситуации вообще?), стоит подумать о том, как это реализовать.

2024-08-03 01:54 UTC, vokinneberg commented on internal/api/router_test.go
> +func Test_list(t *testing.T) {
Стоит так же добавить тесты для новых ручек: `POST /update`, `POST /value`.

2024-08-03 01:54 UTC, vokinneberg commented on internal/api/handler.go
> +	}
Возможно стоит сделать проверку на `nil` первой, так как если она вернет `true` не смысла выполнять остальные?
```suggestion
	if mtr.Value == nil && mtr.Delta == nil {
		c.Status(http.StatusBadRequest)
		return
	}
	if mtr.Delta != nil {
		metricValue = strconv.FormatInt(*mtr.Delta, 10)
	}
	if mtr.Value != nil {
		metricValue = strconv.FormatFloat(*mtr.Value, 'f', -1, 64)
	}
```

2024-08-03 01:54 UTC, vokinneberg commented on internal/api/handler.go
> +	val, _ := hdl.store.Get(mtr.MType, mtr.ID)
Есть ли причина игнорировать bool значение тут и что будет, если оно `false`?

2024-08-03 01:54 UTC, vokinneberg commented on internal/api/middleware.go
> +			defer cr.Close()
Стоит вызывать `defer` сразу после обработки ошбки.
```suggestion
			cr, err := newCompressReader(ctx.Request.Body)
			if err != nil {
				ctx.Writer.WriteHeader(http.StatusInternalServerError)
				return
			}
			defer cr.Close()
			ctx.Request.Body = cr
```

2024-08-03 01:54 UTC, vokinneberg commented on internal/api/middleware.go
> +	return func(ctx *gin.Context) {
Было бы здорово если бы это middleware отдельно логировало запрос и ответ.

2024-08-03 01:54 UTC, vokinneberg commented on internal/store/store.go
> +const CounterName = "counter"
Видел места в коде где все еще используются строки вместо констант, возможно стоит использовать эти константы активнее?

2024-08-03 01:54 UTC, vokinneberg approved these changes

2024-08-04 07:31 UTC, xoxloviwan commented on internal/store/store.go
> +const CounterName = "counter"
а как их переиспользовать, если эти строки в разных пакетах (без дополнительного импорта)?

2024-08-04 07:32 UTC, xoxloviwan commented on internal/api/middleware.go
> +	return func(ctx *gin.Context) {
не совсем понял, в каком то другом формате?

2024-08-04 07:35 UTC, xoxloviwan commented on internal/api/handler.go
> +	val, _ := hdl.store.Get(mtr.MType, mtr.ID)
видимо, это было из соображений, что мы только что добавили это значение через `hdl.store.Add()` (в строке 82) и ситуация когда оно будет `false` - маловероятна в текущей реализации...

2024-08-04 08:14 UTC, xoxloviwan commented on cmd/agent/main.go
> +	}
Упало с ошибкой: `expression in defer must be function call`

Попробовал исправить так, но получаю теперь ответ 400 на запросы
```go
// Compress сжимает слайс байт.
func compressGzip(data []byte) (gzb []byte, err error) {
	var b bytes.Buffer
	// создаём переменную w — в неё будут записываться входящие данные,
	// которые будут сжиматься и сохраняться в bytes.Buffer
	w := gzip.NewWriter(&b)
	defer func() {
		// обязательно нужно вызвать метод Close() — в противном случае часть данных
		// может не записаться в буфер b; если нужно выгрузить все упакованные данные
		// в какой-то момент сжатия, используйте метод Flush()
		if err = w.Close(); err != nil {
			gzb = nil
			err = fmt.Errorf("failed compress data: %v", err)
		}
	}()
	// запись данных
	_, err = w.Write(data)
	if err != nil {
		return nil, fmt.Errorf("failed write data to compress temporary buffer: %v", err)
	}
	// переменная b содержит сжатые данные
	return b.Bytes(), nil
}
```
Пока откатил

2024-08-04 08:23 UTC, xoxloviwan commented on cmd/agent/main.go
> +	}
на самом деле реализация была взята почти "дословно" отсюда [Тема 3/4: Пакет compress. Сжатие данных → Урок 1/3: Оптимизация передачи данных]( https://practicum.yandex.ru/learn/go-advanced/courses/0809706b-b13f-4c30-a11a-f42026c4c00a/sprints/256132/topics/eb964862-ea5d-4880-93e4-6e00eb8f43c8/lessons/9c73cb3d-44c8-4a74-b37a-e191689ae5da/#bcd0e08b-2fc7-4aa7-9db6-92bc0582ff19 )

2024-08-04 08:25 UTC, merged

2024-08-04 17:57 UTC, xoxloviwan commented on internal/api/router.go
> +	for {
Да, он и правда падает при 0 ...

```
panic: non-positive interval for NewTicker

goroutine 1 [running]:
time.NewTicker(0xc0003abed0?)
        C:/Program Files/Go/src/time/tick.go:22 +0xe5
github.com/xoxloviwan/go-monitor/internal/api.RunServer({{0x13fa88c, 0xe}, 0x0, {0x13fc9bc, 0xc}, 0x1, {0x143400c, 0x43}})
        C:/Projects/go-monitor/internal/api/router.go:50 +0x2ca
main.main()
        C:/Projects/go-monitor/cmd/server/main.go:12 +0xc5
```

2024-08-07 02:22 UTC, vokinneberg commented on cmd/agent/main.go
> +	}
Привет, да это моя ошибка вероятно, так как я предполагал, что сначала вызовется `defer`, что вызовет `Flush()` и все данные попадут в буфер перед вызовом `b.Bytes()`, но судя по всему Go выполняет `b.Bytes()` а потом уже defer и return.  Этого я не учел - моя ошибка 😊

2024-08-07 02:25 UTC, vokinneberg commented on internal/store/store.go
> +const CounterName = "counter"
Я именно поэтому сделал название константы заглавной - для того чтобы она была экспортируемая и к ней можно было обращаться из других пакетов. Например в хендлере можно сделать вот так `else if mtr.MType == store.GaugeName`. Или вообще внести в отдельный пакет `constants`, например.

2024-08-07 02:33 UTC, vokinneberg commented on internal/api/middleware.go
> +	return func(ctx *gin.Context) {
Не совсем. Моя идея в том чтобы логировать запрос и ответ отдельно - запрос до обработки, ответ после обработки, так как если произойдет сбой обработки запроса то у нас останется хотя бы лог запроса без лога ответа. В этом случае лог одного запроса/ответа мог бы выглядеть как-то так:
```
REQ [2023-04-15 14:30:45.123] [req-123abc] [GET] [/api/users] [192.168.1.1] [Mozilla/5.0 ...] [0]
RES [2023-04-15 14:30:45.223] [req-123abc] [200] [100ms] [1024]
```
Это не обязательно, конечно. Просто альтернативный подход.

2024-08-07 02:34 UTC, vokinneberg commented on internal/api/middleware.go
> +	return func(ctx *gin.Context) {
Обрати внимание, что здесь логируется ReqID - он будет полезен для сопоставления лога запроса и лога ответа.

2024-08-08 04:49 UTC, xoxloviwan commented on internal/api/middleware.go
> +	return func(ctx *gin.Context) {
Это было полезно, спасибо